name: Deploy Node App via AWS SSM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::374834404321:role/github-actions-ssm-role
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Upload app bundle to EC2 via SSM
      run: |
        aws ssm send-command \
          --instance-ids "${{ secrets.EC2_INSTANCE_ID }}" \
          --document-name "AWS-RunShellScript" \
          --comment "Deploy Node.js app" \
          --parameters commands='[
            "cd /opt/nodeapp",
            "pm2 stop nodeapp || true",
            "rm -rf *",
            "git clone https://github.com/shaik634/poc22.git .",
            "npm install",
            "pm2 start app.js --name nodeapp",
            "pm2 save"
          ]'
