name: Deploy Node App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test || true

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          timeout: 120s
          script_stop: true
          script: |
            cd ${{ secrets.APP_PATH }}
            pm2 stop nodeapp || true
            rm -rf *
            git clone https://github.com/shaik634/poc22.git .
            npm install
            pm2 start app.js --name nodeapp
            pm2 save
